### ISSUE TITLE
Typo in core options

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/bsnes-mercury#15]
Respect accuracy-impacting settings choice is "ON" or "Yes".
Guess "Yes" should be "No".

Balanced core, XMB, win7 x64.

**Comment by Alcaro** [comment]
Tested it on balanced, XMB, Linux x64. Says No/Yes as it should, and as [the source code says](https://github.com/libretro/bsnes-mercury/blob/master/target-libretro/libretro.cpp#L487).

Check your config, it's probably messed up. If not, this bug is in RetroArch; this core is acting as intended and expected. (And even if it is your config, something must've done that, and RetroArch is the only program that has any reason to touch the RetroArch config.)

My guess: At least one menu driver turns Yes/No options like that to checkboxes, then don't convert them back correctly.

**Comment by Tatsuya79** [comment]
The problem is still here with default configs in XMB, but not with RGUI.
Probably an XMB issue then.

**Comment by sergiobenrocha2** [comment]
I can see ON / Yes too.

@Kivutar
